# Generated by Django 5.1.7 on 2025-03-24 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Facebook', models.URLField()),
                ('Twitter', models.URLField()),
                ('Telegram', models.URLField()),
            ],
            options={
                'verbose_name': 'رسانه اجتماعی',
                'verbose_name_plural': 'رسانه های اجتماعی',
            },
        ),
    ]
