# Generated by Django 5.1.7 on 2025-03-26 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_socialmedia'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialmedia',
            name='Address',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='socialmedia',
            name='Email',
            field=models.EmailField(default=0, max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='socialmedia',
            name='Tel',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
