# Generated by Django 5.1.7 on 2025-03-27 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_socialmedia_address_socialmedia_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutDynamic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Description', models.TextField()),
                ('More_details', models.TextField()),
                ('image', models.ImageField(upload_to='AboutDynamic_image')),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
