# Generated by Django 5.1.7 on 2025-03-27 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_aboutdynamic'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aboutdynamic',
            options={'verbose_name': 'اطلاعات متغیر صفحه about', 'verbose_name_plural': 'اطلاعات های متغیر صفحه about'},
        ),
        migrations.RenameField(
            model_name='aboutdynamic',
            old_name='More_details',
            new_name='More_details1',
        ),
        migrations.AddField(
            model_name='aboutdynamic',
            name='More_details2',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='aboutdynamic',
            name='More_details3',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='aboutdynamic',
            name='More_details4',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='aboutdynamic',
            name='More_details5',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
