# Generated by Django 5.1.7 on 2025-03-27 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_aboutdynamic_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactus',
            name='body',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='contactus',
            name='subject',
            field=models.CharField(max_length=100),
        ),
    ]
