# Generated by Django 5.1.7 on 2025-03-28 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_alter_contactus_body_alter_contactus_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactus',
            name='body',
            field=models.TextField(verbose_name='Text'),
        ),
    ]
